### ISSUE TITLE
Allow async execution of service methods

### ISSUE THREAD

**Issue by WaeCo** [dbusjs/node-dbus-next#33]
Correct me if I am wrong but I did not find a way to archive async execution in a Service function.
There is neither a callback nor can I return a Promise in a Service function. 
So all execution inside a method call needs to be synchronous.
This breaks for example if you want to do a database lookup in response the the method call.

Consider following example:
```js
class BluezAgent {
  @method({inSignatur: "os", outSignatur: "b"})
  RequestConfirmation(device, passkey) {
    // check if the key is in the database
    // this is an async operation that returns a promise
    const res = database.isKeyValid(passkey);
    // call a callback once the key is checked
    res.then(callback);
    // or return res as a promise
    return res;
  }
}
```

Implementing the promise return could be as easy as adding an `await` to the handler function call. See: https://github.com/dbusjs/node-dbus-next/blob/a7606341d37605c064246fadaf7b60e181958836/lib/service/handlers.js#L302

**Comment by acrisci** [comment]
Yeah this should definitely be possible. Although I don't use the `await` keyword because I want to support node v6, the idea is the same and it's pretty simple to do this implementation.
