### ISSUE TITLE
getProxyObject doesn't always return

### ISSUE THREAD

**Issue by sunnysidevibes** [dbusjs/node-dbus-next#36]
I'm trying to use this library as a way to consume [signal-cli](https://github.com/AsamK/signal-cli)'s bus service. However, dbus-next won't ever return after calling 
`let obj = await bus.getProxyObject('org.asamk.Signal', '/org/asamk/Signal');`

I also run into a similar issue when running the following lower level code: 
```
  let methodCall = new Message({
    destination: 'org.asamk.Signal',
    path: '/org/asamk/Signal',
    interface: 'org.asamk.Signal',
    member: 'sendMessage',
    signature: 'sass',
    body: ['MessageText2', [], '17876776273']
  });

  let reply = await bus.call(methodCall);
  console.log(reply) #never runs
```

**Comment by acrisci** [comment]
Do you get the same if you use `dbus-send`?

**Comment by ra-rock** [comment]
dbus-send does work.---- On Thu, 19 Sep 2019 09:35:33 -0400  Tony Crisci<notifications@github.com> wrote ----Do you get the same if you use dbus-send?

**Comment by ra-rock** [comment]
`dbus-send` does work. 

    dbus-send --session --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:[MESSAGE] array:string: string:[RECIPIENT]
    method return sender=:1.38 -> dest=:1.43 reply_serial=2

**Comment by djusHa** [comment]
Hi,
i can confirm this. No return if using getPorxyObject() on signal-cli.
(https://github.com/AsamK/signal-cli)[https://github.com/AsamK/signal-cli]

```
const SIGNAL_BUSNAME = 'org.asamk.Signal';
  const SIGNAL_OBJECTPATH = '/org/asamk/Signal';

  let obj = await bus.getProxyObject(SIGNAL_BUSNAME, SIGNAL_OBJECTPATH);
```

**Comment by acrisci** [comment]
It's hard for me to set up because I don't have signal right now and I have to go through the whole process to test it.

Try to run that while running `dbus-monitor` and see if there's anything interesting.

**Comment by djusHa** [comment]
you don't necesserily have to register signal on mobile phone, "normal" phone number does it too.

Just: 
`signal-cli -u <phonenumber in int. format> register  --voice`

after that, there will be a call that tells you the verification number.

Here you can unregister the number: (https://signal.org/textsecure/unregister/)[https://signal.org/textsecure/unregister/]

**Comment by djusHa** [comment]
Have looked with dbus-monitor while running the script, nothing interesting...

**Comment by acrisci** [comment]
Ok I see the issue. The unmarshaller doesn't handle big endian messages. Everything else I've tested uses little endian.
