### ISSUE TITLE
Message interface in typescript doesn't match up with class.

### ISSUE THREAD

**Issue by normano** [dbusjs/node-dbus-next#37]
Message interface here: https://github.com/dbusjs/node-dbus-next/blob/bbef4550d9e666d2260be49137b1747815158e5f/types.d.ts#L50

In the help: 
```
let methodCall = new Message({
  destination: 'org.freedesktop.DBus',
  path: '/org/freedesktop/DBus',
  interface: 'org.freedesktop.DBus',
  member: 'ListNames'
});
```

Message is exposed as interface in typescript file, so I have to do this in order to get the class.
```
import dbus from "dbus-next";
let Message = (<any>dbus).Message;
```

Looks like an unintended mismatch.

**Comment by acrisci** [comment]
@WaeCo did those typings. Maybe he can help.

**Comment by WaeCo** [comment]
You are right, there are two Message interfaces. The internal DBus one and the external low level API one.
I will make a PR to fix it.
