### ISSUE TITLE
Clean up?

### ISSUE THREAD

**Issue by anon9876** [dbusjs/node-dbus-next#39]
What's the proper way to clean up an interface? I'm using dbus-next (thank you, I appreciate it) for a NetworkManager implementation in a long running process. There is a lot of object turnover; when I set up an object I add a listener to 'PropertiesChanged' and when I destroy it I remove all listeners, but my process inevitably crashes on the following unhandled error:

```
Connection ":1.104" is not allowed to add more match rules (increase limits in configuration file if required; max_match_rules_per_connection=2048)

DBusError: Connection ":1.104" is not allowed to add more match rules (increase limits in configuration file if required; max_match_rules_per_connection=2048)
    at _methodReturnHandlers.(anonymous function) (/path/to/external/node_modules/dbus-next/lib/bus.js:326:27)
    at handleMessage (/path/to/external/node_modules/dbus-next/lib/bus.js:86:11)
    at EventEmitter.MessageBus.conn.on (/path/to/external/node_modules/dbus-next/lib/bus.js:135:9)
    at EventEmitter.emit (events.js:189:13)
    at /path/to/external/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/path/to/external/node_modules/dbus-next/lib/message.js:55:9)
```

Edit/Appended: I use the same `require('dbus-next').systemBus()` instance for every object (AccessPoint,Connection,Device,etc), would it be recommended to use a new instance in each case?

**Comment by acrisci** [comment]
Could you try with master branch and see if you still get the same error?

Ref bd08f64394d30f1b133ddabbbc0c018b6edced24

**Comment by acrisci** [comment]
Looking at that a bit more carefully, it won't solve this problem.

What should happen is that when a listener is added, a match should be added and when a listener is removed, a match should be removed. Then you can do cleanup by just removing event listeners which you have to do anyway.

**Comment by anon9876** [comment]
So removing any manually added listeners is the proper way, there's no additional cleanup() or destroy() methods that I should be calling? Your suspicion then would be that somewhere I'm registering a listener I'm not removing?

**Comment by acrisci** [comment]
I think it's a library error. Try and see if #40 fixes the issue.

**Comment by anon9876** [comment]
Switching from the npm repo to this github one seems to have cleared up the issue, thanks.
