### ISSUE TITLE
TypeScript definition not included in npm package

### ISSUE THREAD

**Issue by 6XGate** [dbusjs/node-dbus-next#44]
The `types.d.ts` file is referenced in the `package.json` but the file not included when installing the package via _npm_.

**Comment by acrisci** [comment]
Yeah that should be included.

**Comment by acrisci** [comment]
Let me know if I did that right.

**Comment by 6XGate** [comment]
Looks right to me

**Comment by eventualbuddha** [comment]
This may be fixed on master, but still not published.

**Comment by acrisci** [comment]
Just waiting if there was more to a release than just this, but I guess I can publish it.

**Comment by eventualbuddha** [comment]
Here's something for you to include in the release: #45.
