### ISSUE TITLE
NetworkManager

### ISSUE THREAD

**Issue by cronos-dcrop** [dbusjs/node-dbus-next#61]
how can i listen for messages when wifi and LAN adapters are connected/disconnect?

i already tried:

`// add a custom handler for a particular method
bus.addMethodHandler((msg) => {
    if (String(msg.path).startsWith('/org/freedesktop/NetworkManager')) {
        console.log(msg);
    }
});`

`bus.on('message', (msg) => {
    console.log('got a message: ', msg);
});`

but no success.

**Comment by acrisci** [comment]
Use the high level client or if you use the low level client, you have to add a match rule.

https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-routing-match-rules

**Comment by cronos-dcrop** [comment]
@acrisci got it! thank you!
