### ISSUE TITLE
Additional interfaces created with bus.export()

### ISSUE THREAD

**Issue by SimonGAndrews** [dbusjs/node-dbus-next#62]
Hello,  Please can you help me to understand this issue I am having when attempting to export multiple interfaces in a single JavaScript App.  I am finding in the case where two or more bus.export() are used, investigation of the resulting  D-BUS structure in d-feet shows that multiple interfaces have been exported/created for each bus.export().  For example in this simplified case:
````javascript
const EventEmitter = require ('events');
const dbus = require('dbus-next');
const {Interface} = dbus.interface;

class Iface01 extends Interface {
    constructor() { 
      super('org.test.Interface1'); 
    }
}
  
class Iface02 extends Interface {
    constructor() { 
      super('org.test.Interface2');
    }
}

var bus = dbus.systemBus(); 
interface1 = new Iface01();
interface2 = new Iface02();

async function main() {
 await bus.requestName('org.test.services');
 bus.export('/org/test/path1', interface1); 
 bus.export('/org/test/path2', interface2);
}

main().catch(console.log);
````

the d-feet output looks like this
![InkedexportIssue02](https://user-images.githubusercontent.com/55559464/104854884-25443b00-5901-11eb-99ae-5b372b982daf.jpg)

where it appears that each of the two interfaces has been created four times.

further observations are:
 - the issue on ly occurs when multiple bus.export() are used.
 - if the two interfaces were to be exported to the same path, then the repeating does not occur.
 - the number or replications is proportional to the number of / in the path for the given interface export.

I am trying to create the interface structure needed to create a bluetooth GATT application structure as set out in the last section of  https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt

However am struggling to get over this apparent issue.  Thanks in advance for any advice.

happy to investigate further and report given any direction.  
Regards,  Simon

**Comment by acrisci** [comment]
Test the actual functionality of calling the methods or whatever and see if that works. The problem might just be with the introspection that's created and nothing else.

Would you please post the full xml representation text that's generated for the object? Use `org.freedesktop.DBus.Introspect` method on the object to get that.

**Comment by SimonGAndrews** [comment]
Thanks for the response Tony,

Ive run the Introspect method as per this screen shot and attach four files below.  Two for path1 and two for path2.   The XML looks the same by eye for the other path1's or path2's      (let me know if not what youve asked for)

[introspect_path1_1.txt](https://github.com/dbusjs/node-dbus-next/files/5826988/introspect_path1_1.txt)
[introspect_path1_2.txt](https://github.com/dbusjs/node-dbus-next/files/5826989/introspect_path1_2.txt)
[introspect_path2_1.txt](https://github.com/dbusjs/node-dbus-next/files/5826990/introspect_path2_1.txt)
[introspect_path2_2.txt](https://github.com/dbusjs/node-dbus-next/files/5826991/introspect_path2_2.txt)





![exportIssue_introspectExport01](https://user-images.githubusercontent.com/55559464/104858522-c4742d00-5917-11eb-8b5e-c86528b26317.png)

Regarding testing the functionality , I will continue tomorrow, so far the actual methods and properties seem to be exported correctly , they are just repeated.   However , Im still trying, but the bluez D-BUS method I am depending on is org.bluez.GattManager1 RegisterApplication  (in link above) which appears to rely on the correct application hierarchy.  Im not successful yet , which could be due to the repeats in the structure or some other issue in my content within the structure.  I will continue and let you know.  Thanks again 
 PS my first d-Bus /  bluez project so its a tricky stack for me in any event.

**Comment by acrisci** [comment]
The nodes are being duplicated in the introspection at the two root nodes, `/` and `/org`. D-feet chooses both of those paths to recurse upwards and thinks there are four interfaces. However at the top node, it correctly says there are only two interfaces. We can fix this pretty easily in the introspection generation code. I don't think there are any other problems.

```
~> dbus-send --print-reply --session --dest=org.test.services /org org.freedesktop.DBus.Introspectable.Introspect 
method return time=1611018003.475970 sender=:1.321 -> destination=:1.444 serial=51 reply_serial=2
   string "<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <node name="test"/>
  <node name="test"/>
</node>"

~> dbus-send --print-reply --session --dest=org.test.services / org.freedesktop.DBus.Introspectable.Introspect 
method return time=1611018028.704418 sender=:1.321 -> destination=:1.445 serial=52 reply_serial=2
   string "<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <node name="org"/>
  <node name="org"/>
</node>"
```

**Comment by SimonGAndrews** [comment]
Thanks very much for sorting this.
Ive updated my end and in my other examples the issue is not occurring also. 
Brilliant.
And thanks for the patience with a dbus newbie.
Regards,  Simon
